import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../../../view/styles/Home.module.css';
import Header from '../../../view/components/header';
import Footer from '../../../view/components/footer';
import AnimeList from '../../../view/components/animeList';
import { handleFullAnimeFetch } from '../../../model/anime';
import { useEffect } from 'react';
import { IAnime } from '../../index';

interface IFullAnime extends IAnime {
    averageScore: number;
    coverImage: { large: string; extraLarge: string };
    bannerImage: string;
    status: string;
    trailer: any;
    endDate: {
        year: number;
        month: number;
        day: number;
    };
}

export interface IAnimeListProps {
    anime: IFullAnime;
}

interface IFullAnimePageProps {
    anime: IFullAnime;
}
const Home: NextPage<IFullAnimePageProps> = ({ anime }) => {
    console.log(anime);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name=' blue description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header />
            <main className={styles.main}>
                <div>Аниме</div>
            </main>

            <Footer />
        </div>
    );
};
export const getServerSideProps: GetServerSideProps<
    IFullAnimePageProps
> = async (context) => {
    const id = context?.params?.id;
    const anime = await handleFullAnimeFetch(Number(id));
    return {
        props: { anime: anime.data.Media },
    };
};
export default Home;
