import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import styles from '../view/styles/Home.module.css';
import Header from '../view/components/header';
import Footer from '../view/components/footer';
import AnimeList from '../view/components/animeList';
import { handleShortAnimeFetch } from '../model/anime';

export interface IAnime {
    averageScore: number;
    coverImage: { large: string };
    description: string;
    genres: string[];
    id: number;
    title: { romaji: string };
}

export interface IAnimeListProps {
    animes: IAnime[];
    title: string;
    type: 'column' | 'row';
}

interface MainPageProps {
    animes: IAnime[];
}
const Home: NextPage<MainPageProps> = ({ animes }) => {
    const choosedAnimes = animes.slice(0, 5);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name=' blue description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header />
            <main className={styles.main}>
                <AnimeList
                    type='column'
                    title='Популярные'
                    animes={choosedAnimes}
                />
            </main>

            <Footer />
        </div>
    );
};
export const getServerSideProps: GetServerSideProps<
    MainPageProps
> = async () => {
    const animes = await handleShortAnimeFetch();

    return {
        props: { animes: animes.data.Page.media },
    };
};
export default Home;
